name: flutter_app_update_manager_example
description: "Example app demonstrating Flutter App Update Manager features"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app_update_manager:
    path: ../
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 