name: flutter_app_update_manager
description: "A Powerful Flutter Package To Easily Manage In-App Updates Using Firebase Firestore With Multiple Dialog Styles and Custom Dialog Support."
version: 0.1.6
homepage: https://github.com/muzzammil763/flutter_app_update_manager
repository: https://github.com/muzzammil763/flutter_app_update_manager

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.0
  cloud_firestore_platform_interface: ^6.6.12
  firebase_core: ^3.0.0
